image:
  # This image is built upon the following Dockerfile: .gitpod.Dockerfile
  ghcr.io/lpiot/gitpod-workspace:main
  # You can dynamically build the image when you create a new GitPod workspace with the following lines
  # gitpod/workspace-full
  # file: .gitpod.Dockerfile
additionalRepositories:
    - url: https://github.com/musk8teers/container.training.git
      # checkoutLocation is optional and relative to /workspaces.
      # by default the location defaults to the repository name.
      checkoutLocation: 'musk8teers/container.training'
    - url: https://github.com/musk8teers/spring-music.git
      # checkoutLocation is optional and relative to /workspaces.
      # by default the location defaults to the repository name.
      checkoutLocation: 'musk8teers/spring-music'
tasks:
  - name: workspace configuration
    command: |
      mkdir -p /home/gitpod/.ssh
      cp -pr /workspace/gitpod-workspace/ssh-config /home/gitpod/.ssh/config
  - name: pre-requisite for container.training
    before: |
      echo "pre-requisite for container.training"
      echo "make /dev/stderr writable"
      sudo chmod go+rw /dev/pts/?
      echo "Activate SSH agent"
      eval $(ssh-agent) ; ssh-add && echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}"
      echo "Configure Digital Ocean CLI"
      doctl auth init --access-token $(tail -1 /workspace/.secrets/gitpod-digitalocean_highfive-m6.token)
vscode:
  extensions:
    - yzhang.markdown-all-in-one
    - Gruntfuggly.todo-tree
    - hashicorp.terraform
workspaceLocation:
  "."
